spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}